"""mulberry32: the same random numbers here as in the studio, forever.

A scene that uses seeded randomness — a dot field's positions, a noise
patch's grain — must render identically in the studio where it was designed
and in the experiment that runs it. That only holds if both use the same
generator, bit for bit.

This is a port of illusion-studio's ``src/rng.ts``. It is *not*
``numpy.random``, and swapping it for one would silently change every stored
scene's appearance. The pinned sequences in the tests are generated by
running the TypeScript itself.

The arithmetic below is JavaScript's, emulated: 32-bit wraparound on every
operation, unsigned shifts, and ``Math.imul``'s low-32-bits multiply. Python
integers are arbitrary precision, so each step masks explicitly — those masks
are the port, not decoration.
"""

from __future__ import annotations

from collections.abc import Callable

UINT32 = 0xFFFFFFFF
# The generator's magic increment, from the published mulberry32.
INCREMENT = 0x6D2B79F5
# 2**32: what the final 32-bit integer is divided by to land in [0, 1).
SCALE = 4294967296.0


def _imul(a: int, b: int) -> int:
    """JavaScript's ``Math.imul``: multiply, keep the low 32 bits.

    The result is used only in xors and additions that are themselves
    truncated to 32 bits, so the unsigned low half is the same bit pattern
    JavaScript's signed result would give.
    """
    return (a * b) & UINT32


def mulberry32(seed: int) -> Callable[[], float]:
    """A generator function producing floats in [0, 1).

    Returns a closure, like the TypeScript does, because the sequence is
    stateful: ``rng(seed)`` is its first value and ``rngN(seed, n)`` the
    (n+1)-th, and both are defined in terms of stepping this same state.
    """
    state = int(seed) & UINT32

    def next_value() -> float:
        nonlocal state
        state = (state + INCREMENT) & UINT32
        # Each line mirrors one line of the TS; the masks are where
        # JavaScript's implicit 32-bit truncation happens.
        t = _imul(state ^ (state >> 15), 1 | state)
        t = ((t + _imul(t ^ (t >> 7), 61 | t)) & UINT32) ^ t
        return ((t ^ (t >> 14)) & UINT32) / SCALE

    return next_value


def to_uint32(number: float) -> int:
    """JavaScript's ToUint32, which is what ``x >>> 0`` and every bitwise
    operator apply to their operands.

    The studio's dot seeding is written as ``(seed ^ (i * 2654435761)) >>> 0``.
    That multiply is an ordinary float multiply — not ``Math.imul`` — and the
    ``^`` is what truncates it to 32 bits. Doing the multiply in Python's
    arbitrary-precision integers and skipping the truncation gives a different
    seed for every dot past the first few, i.e. a different stimulus.
    """
    truncated = int(number)  # ToInteger: truncate toward zero
    return truncated & UINT32


def rng(seed: float) -> float:
    """The first sample for this seed — the scene format's ``rng(seed)``."""
    return mulberry32(int(seed))()


def rng_n(seed: float, n: float) -> float:
    """The (n+1)-th sample — the scene format's ``rngN(seed, n)``.

    ``n`` is clamped to 100 000 exactly as the TypeScript clamps it: an
    expression asking for the billionth sample would otherwise hang a render
    rather than draw something wrong, which is worse.
    """
    generator = mulberry32(int(seed))
    steps = max(0, min(100_000, int(n)))
    for _ in range(steps):
        generator()
    return generator()
