"""The dot field, pinned against illusion-studio's own arithmetic.

A random-dot kinematogram is the load-bearing stimulus for a whole class of
experiment: the dependent variable is a coherence threshold, so *which* dots
carry the signal and *where* every dot is are the measurement, not decoration.
This is the strongest pin in the renderer's suite.

``dotfield_parity.json`` is generated by running the studio's own
``drawDotField`` maths (procedural.ts) under Node with the studio's
``mulberry32``. It is not alhazen's output recorded — that would only pin the
bug that was there.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from alhazen.scenes.render import RenderContext, dot_field_positions

FIXTURE = json.loads(
    (Path(__file__).parents[1] / "fixtures" / "scenes" / "dotfield_parity.json").read_text()
)


def ours(element: dict, time: float):
    return dot_field_positions(element, RenderContext(width=200, height=150, time=time))


@pytest.mark.parametrize("case", sorted(FIXTURE))
def test_every_dot_lands_where_the_studio_puts_it(case):
    body = FIXTURE[case]
    for time, expected in zip(body["times"], body["positions"], strict=True):
        computed = ours(body["element"], time)
        assert len(computed) == len(expected), f"{case} at t={time}: wrong dot count"
        for index, (mine, theirs) in enumerate(zip(computed, expected, strict=True)):
            if theirs is None:
                assert mine is None, f"{case} at t={time}: dot {index} should have left"
                continue
            assert mine is not None, f"{case} at t={time}: dot {index} should still be here"
            assert mine[0] == pytest.approx(theirs[0], abs=1e-9)
            assert mine[1] == pytest.approx(theirs[1], abs=1e-9)


class TestTheRulesThatWereWrong:
    def element(self, **overrides):
        return {
            "type": "dotField",
            "cx": 100,
            "cy": 75,
            "width": 120,
            "height": 100,
            "count": 20,
            "coherence": 0.5,
            "speed": 60,
            "direction": 0.0,
            "seed": 7,
            **overrides,
        }

    def test_the_signal_set_is_the_first_dots_by_index(self):
        """Not a per-dot coin flip against coherence. A coin flip gives the
        right *expected* coherence and a field whose actual signal count
        varies frame to frame — which is exactly what a coherence threshold
        measures."""
        element = self.element(coherence=0.5, count=20)
        start = ours(element, 0.0)
        later = ours(element, 0.5)

        # The first 10 dots all moved along direction 0 (+x, wrapped); their
        # y coordinates are unchanged.
        for index in range(10):
            assert later[index][1] == pytest.approx(start[index][1], abs=1e-9)
        # At least one of the remaining ten moved off its starting row.
        assert any(abs(later[index][1] - start[index][1]) > 1e-6 for index in range(10, 20))

    def test_coherence_one_makes_every_dot_signal(self):
        element = self.element(coherence=1.0, count=8)
        start, later = ours(element, 0.0), ours(element, 0.25)
        for before, after in zip(start, later, strict=True):
            assert after[1] == pytest.approx(before[1], abs=1e-9)

    def test_each_dot_draws_from_its_own_stream(self):
        """Changing the count must not move the dots that were already there.
        One shared stream makes every dot's position depend on how many dots
        came before it."""
        few = ours(self.element(count=5), 0.0)
        many = ours(self.element(count=50), 0.0)

        # coherence 0.5 of 5 is 3 signal dots and of 50 is 25, so only the
        # positions (not the headings) are comparable — at t=0 that is all
        # there is.
        for index in range(5):
            assert many[index] == pytest.approx(few[index], abs=1e-9)

    def test_speed_defaults_to_sixty_pixels_a_second(self):
        """Defaulting to zero made every scene that omits `speed` a still
        image — an RDK with no motion in it."""
        element = self.element(coherence=1.0, direction=0.0, count=4)
        element.pop("speed")
        start = ours(element, 0.0)
        later = ours(element, 0.1)

        # 60 px/s for 0.1 s is 6 px along +x, wrapped into a 120 px aperture.
        for before, after in zip(start, later, strict=True):
            moved = (after[0] - before[0]) % 120
            assert moved == pytest.approx(6.0, abs=1e-6)

    def test_a_lifetime_respawns_the_dot(self):
        """Without lifetime support a dot travels forever; the studio rebirths
        it each cycle at a position its re-seeded stream chooses."""
        element = self.element(coherence=1.0, lifetime=0.3, count=6)
        before = ours(element, 0.29)
        after = ours(element, 0.31)

        # Crossing a lifetime boundary must move at least one dot further than
        # 0.02 s of travel (1.2 px) could account for.
        jumps = [math.hypot(a[0] - b[0], a[1] - b[1]) for a, b in zip(after, before, strict=True)]
        assert max(jumps) > 5.0

    def test_wrap_false_drops_a_dot_that_leaves(self):
        element = self.element(coherence=1.0, direction=0.0, wrap=False, speed=200, count=8)
        assert all(position is not None for position in ours(element, 0.0))
        assert any(position is None for position in ours(element, 1.0))

    def test_wrap_true_keeps_the_field_full(self):
        element = self.element(coherence=1.0, direction=0.0, speed=200, count=8)
        assert all(position is not None for position in ours(element, 1.0))

    def test_every_dot_stays_inside_the_aperture_when_wrapped(self):
        element = self.element(coherence=0.5, speed=300, count=40)
        for position in ours(element, 3.7):
            assert position is not None
            assert 40.0 <= position[0] <= 160.0
            assert 25.0 <= position[1] <= 125.0


class TestSeeding:
    def test_the_index_hash_is_truncated_to_32_bits(self):
        """`i * 2654435761` is an ordinary float multiply in JavaScript; the
        `^` that follows is what truncates it. Doing the multiply in Python's
        arbitrary-precision integers and skipping the truncation gives a
        different seed — and so a different stimulus — for all but the first
        few dots."""
        from alhazen.scenes.rng import to_uint32

        assert to_uint32(2 * 2654435761) == (2 * 2654435761) & 0xFFFFFFFF
        assert to_uint32(2 * 2654435761) != 2 * 2654435761

    def test_a_different_seed_is_a_different_field(self):
        first = ours(
            {
                "type": "dotField",
                "cx": 100,
                "cy": 75,
                "width": 100,
                "height": 100,
                "count": 10,
                "seed": 1,
            },
            0.0,
        )
        second = ours(
            {
                "type": "dotField",
                "cx": 100,
                "cy": 75,
                "width": 100,
                "height": 100,
                "count": 10,
                "seed": 2,
            },
            0.0,
        )
        assert not np.allclose(np.array(first), np.array(second))
